# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastexo', '0003_blanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacklog',
            name='stack',
        ),
        migrations.AddField(
            model_name='stacklog',
            name='stack_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
