# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hastexo', '0004_auto_20190715_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='hook_events',
            field=jsonfield.fields.JSONField(default="null"),
        ),
        migrations.AddField(
            model_name='stack',
            name='hook_script',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='providers',
            field=jsonfield.fields.JSONField(default="null"),
        ),
        migrations.AddField(
            model_name='stack',
            name='run',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stacklog',
            name='hook_events',
            field=jsonfield.fields.JSONField(default="null"),
        ),
        migrations.AddField(
            model_name='stacklog',
            name='hook_script',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stacklog',
            name='providers',
            field=jsonfield.fields.JSONField(default="null"),
        ),
        migrations.AddField(
            model_name='stacklog',
            name='run',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
