# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-07 13:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hastexo', '0005_auto_20190811_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='hook_events',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.RunSQL(
            "UPDATE hastexo_stack SET hook_events = '{}' WHERE hook_events = '\"null\"';",  # noqa: E501
            "UPDATE hastexo_stack SET hook_events = '\"null\"' WHERE hook_events = '{}';",  # noqa: E501
        ),
        migrations.AlterField(
            model_name='stack',
            name='providers',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.RunSQL(
            "UPDATE hastexo_stack SET providers = '[]' WHERE providers = '\"null\"';",  # noqa: E501
            "UPDATE hastexo_stack SET providers = '\"null\"' WHERE providers = '[]';",  # noqa: E501
        ),
        migrations.AlterField(
            model_name='stacklog',
            name='hook_events',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stacklog',
            name='providers',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
