# Generated by Django 2.2.16 on 2021-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastexo', '0008_add_database_defaults_for_stack_key_and_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
